import Head from "next/head";
import Layout from "./layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Trouble Partner</title>
        <meta name="description" content="Generated by Trouble Partner" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className=" ">
          <div className="container mx-auto px-4 min-h-[200px]">
            fsdfdfsdffs
          </div>
        </div>
      </Layout>
    </>
  );
}
