import Head from "next/head";
import Layout from "./layout";
import Image from "next/image";
import Card from "@/components/card";
import { BiChevronRight, BiChevronLeft } from "react-icons/bi";
import { useSession } from "next-auth/react";
import { useAppContext } from "@/context";
import { signIn } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import axios from "axios";
import { useState } from "react";
import formatDate from "@/helpers/formatDate";
import Swal from "sweetalert2";
import AdSense from "react-adsense";

export default function Home() {
  const { user, setUser, loading, setLoading } = useAppContext();
  const [posts, setPosts] = useState([]);
  const { push } = useRouter();

  const { data: session, status } = useSession();

  useEffect(() => {
    axios({
      method: "GET",
      url: "/api/posts",
    })
      .then((res) => {
        setPosts(res.data.data);
      })
      .catch((err) => {
        Swal.fire("Error!", "Something went wrong.", "error");
      });
  }, [session]);

  const createPostPageHandle = () => {
    if (status === "authenticated") {
      return () => {
        push("/create-post");
      };
    } else {
      return () => {
        signIn("google");
      };
    }
  };

  return (
    <>
      <Head>
        <title>Trouble Partner</title>
        <meta name="description" content="Generated by Trouble Partner" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className=" py-20">
          <div className="md:container mx-auto px-4 min-h-[200px]">
            <section className="flex justify-center">
              <div className="flex flex-col items-center max-w-2xl">
                <h2 className="text-slate-700 font-maxbold text-center text-4xl sm:text-5xl md:text-6xl">
                  Trouble Partner
                </h2>
                <p className="text-slate-600 text-center font-semibold text-lg lg:text-2xl relative inline-flex justify-center">
                  Your problem is our problem.
                </p>
                <p className="text-center leading-5 px-4 text-slate-800/60 mt-4 font-medium text-sm md:text-base max-w-lg">
                  Share your problem, either as yourself or anonymously. People
                  will connect with you and find solutions. they&apos;ll find
                  it. That&apos;s how simple it is. That&apos;s how beautiful it
                  is. That&apos;s how it is. as easy as that. That&apos;s how
                  safe it is.
                </p>
                <button
                  onClick={createPostPageHandle()}
                  className="bg-blue-300  text-blue-700 font-bold py-2 px-4 rounded border-blue-600 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 mt-8 outline-dashed outline-2 outline-blue-700/50 outline-offset-4"
                >
                  Share Your Trouble
                </button>
              </div>
            </section>

            <section className="mt-20 flex flex-col sm:grid sm:grid-cols-12 gap-4">
              <div className="col-span-2 px-4 py-4 relative hidden lg:flex">
                <div className="h-40 sticky top-12 w-full flex justify-center items-center text-white ">
                  <AdSense.Google
                    client="ca-pub-8831973080518055"
                    slot="5352367283"
                  />
                </div>
              </div>
              <div className="cardArea flex flex-col items-center col-span-12 lg:col-span-8 gap-6 ">
                {posts.map((post) => (
                  <Card
                    key={post._id}
                    id={post._id}
                    image={post.user.image}
                    name={post.user.name}
                    text={post.text}
                    slug={post.slug}
                    privacyStatus={post.privacyStatus}
                    time={formatDate(post.createdAt)}
                    comment={post.numComments}
                  />
                ))}

                <div className="pagination flex gap-2 mt-6">
                  <button className="bg-white  text-blue-700/70 font-bold  rounded border-blue-700/70 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 w-10 h-10 flex justify-center items-center">
                    <BiChevronLeft fontSize={32} />
                  </button>
                  <button className="bg-white  text-blue-700/70 font-extrabold  rounded border-blue-700/70 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 w-10 h-10 flex justify-center items-center">
                    1
                  </button>
                  <button className="bg-white  text-blue-700/70 font-extrabold  rounded border-blue-700/70 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 w-10 h-10 flex justify-center items-center">
                    2
                  </button>
                  <button className="bg-white  text-blue-700/70 font-extrabold  rounded border-blue-700/70 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 w-10 h-10 flex justify-center items-center">
                    3
                  </button>
                  <button className="bg-white  text-blue-700/70 font-extrabold  rounded border-blue-700/70 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 w-10 h-10 flex justify-center items-center">
                    4
                  </button>
                  <button className="bg-white  text-blue-700/70 font-bold  rounded border-blue-700/70 duration-300 hover:text-blue-50 hover:bg-blue-700 border-2  hover:shadow-lg hover:shadow-blue-600/50 w-10 h-10 flex justify-center items-center">
                    <BiChevronRight fontSize={32} />
                  </button>
                </div>
              </div>
              <div className="col-span-2 px-4 py-4 relative hidden lg:flex">
                <div className="h-40 sticky top-12 w-full flex justify-center items-center text-white ">
                  <AdSense.Google
                    client="ca-pub-8831973080518055"
                    slot="5352367283"
                  />
                </div>
              </div>
            </section>
          </div>
        </div>
      </Layout>
      {loading && (
        <div className="fixed top-0 left-0 w-full h-full bg-white z-50 flex justify-center items-center">
          <div
            className="inline-block h-16 w-16 animate-spin rounded-full border-8 border-solid border-blue-600  border-r-transparent align-[-0.125em] motion-reduce:animate-[spin_1.5s_linear_infinite]"
            role="status"
          >
            <span className="!absolute !-m-px !h-px !w-px !overflow-hidden !whitespace-nowrap !border-0 !p-0 ![clip:rect(0,0,0,0)]">
              Loading...
            </span>
          </div>
        </div>
      )}
    </>
  );
}
